ATTR_STYLE = '__estilo__'
ATTR_NEIGHBORS = '__vecinos__'
ATTR_EDGES = '__aristas__'
ATTR_POS = '__pos__'
ATTR_POS_VP = '__POS__'
ATTR_DISP = '__desp__'
ATTR_LAYERED = '__acomodado__'

FORM_CIRCLE = 'circulo'
FORM_SQUARE = 'cuadro'
FORM_CROSS = 'cruz'
FORM_CROSSOUT = 'tache'
FORM_TRIANGLE = 'triangulo'

STYLE_COLOR = '_color'
STYLE_DOTTED = '_discontinuo?'
STYLE_SIZE = '_tamaño'
STYLE_SHOW_ID = '_mostrarId?'
STYLE_ANTIALIAS = '_antialias'
STYLE_FORM = 'forma'
STYLE_BORDERCOLOR = 'color_borde'
STYLE_FILLCOLOR = 'color_relleno'
STYLE_THICKNESS = 'grosor'
STYLE_FILLED = 'relleno?'
STYLE_BORDERED = 'borde?'
STYLE_SCALED = 'escalar?'
STYLE_SHOW_ID = 'mostrarId?'

STYLE_BACKGROUND = '_fondo'
STYLE_SHOW_EXT = '_mostrarExt'
STYLE_SHOW_VP = '_mostrarVP'
STYLE_APPLIED = '_estiloAplicado?'
STYLE_LINECOLOR = '_estiloColorLinea'

NNAME_PREFIX = 'nodo_'
X_ATTR = '__x__'
Y_ATTR = '__y__'
